jenkins:
  # $JENKINS_URL
  ## url: "https://10.10.10.10:8080"
  view: "QA-CAASP"
  authentication:
    enabled: True
    # $JENKINS_USERNAME
    ## user: "jenkins_user"

    # $JENKINS_PASSWORD
    ## password: "jenkins_passowrd"

    # $JENKINS_CRUMB
    ## crumb: "Jenkins-Crumb:e3d49c085347bf2cc24aca382f698a70"

parameters:
  # Name of the stack to test, caasp|microos
  stack: "caasp"

  # IMAGE parameter
  image: True

  # IMAGE_URL parameter
  image_url: False

jobs:
  # Hyper-V jobs
  hyperv:
    - name: "qa-caasp-hyperv-1m2w-conformance"
      parameters:
        MASTER_COUNT: 1
        WORKER_COUNT: 2

    - name: "qa-caasp-hyperv-3m2w-conformance"
      parameters:
        MASTER_COUNT: 3
        WORKER_COUNT: 2

  # VMware jobs
  vmware:
    - name: "qa-caasp-vmware-1m2w-conformance"
      parameters:
        MASTER_COUNT: 1
        WORKER_COUNT: 2

    - name: "qa-caasp-vmware-3m2w-conformance"
      parameters:
        MASTER_COUNT: 3
        WORKER_COUNT: 2

  # OpenStack jobs
  openstack:
    - name: "qa-caasp-openstack-1m2w-conformance"
      parameters:
        MASTER_COUNT: 1
        WORKER_COUNT: 2

    - name: "qa-caasp-openstack-3m2w-conformance"
      parameters:
        MASTER_COUNT: 3
        WORKER_COUNT: 2
