jenkins:
  # $JENKINS_URL
  ## url: "https://10.10.10.10:8080"
  view: "QA-CAASP"
  authentication:
    enabled: True
    # $JENKINS_USERNAME
    ## user: "jenkins_user"

    # $JENKINS_PASSWORD
    ## password: "jenkins_passowrd"

    # $JENKINS_CRUMB
    ## crumb: "Jenkins-Crumb:e3d49c085347bf2cc24aca382f698a70"

parameters:
  # Name of the stack to test, caasp|microos
  stack: "caasp"

  # IMAGE parameter
  image: True

  # IMAGE_URL parameter
  image_url: True

jobs:
  hyperv:
    - name: "qa-caasp-hyperv-push-image"

  openstack:
    - name: "qa-caasp-openstack-push-image"
  
  #kvm:
  #  - name: "kvm-push-image"

  vmware:
    - name: "qa-caasp-vmware-push-image"

  #xen:
  #  - name: "xen-push-image"
