version: '3.4'

services:
  jenkins-server:
    build: ./
    container_name: jenkins-server
    environment:
      - JENKINS_URL=http://10.84.152.30:8080
      - CASC_JENKINS_CONFIG=/jenkins.yaml
      - DOCKER_OPTS="-H unix:///var/run/docker.sock"
    volumes:
      - /jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    secrets:
      - hyperv-user
      - hyperv-password
      - jenkins-user
      - jenkins-password
      - openstack-openrc
      - vmware-user
      - vmware-password
      - jenkins-ssh-private-key

secrets:
  hyperv-user:
    file: ./secrets/hyperv-user
  hyperv-password:
    file: ./secrets/hyperv-password
  openstack-openrc:
    file: ./secrets/openstack-openrc
  jenkins-user:
    file: ./secrets/jenkins-user
  jenkins-password:
    file: ./secrets/jenkins-password
  vmware-user:
    file: ./secrets/vmware-user
  vmware-password:
    file: ./secrets/vmware-password
  jenkins-ssh-private-key:
    file: ./secrets/jenkins-ssh-private-key
